# Generated by Django 4.2.4 on 2023-08-08 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=100)),
                ("url_flux_audio_video", models.URLField()),
                (
                    "heure_debut",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
